- type: job
  id: BorgRedGeneric
  name: job-name-borg-red-generic
  description: job-name-borg-red-generic-desc
  playTimeTracker: JobBorgBlue
  icon: JobIconBorg
  supervisors: job-supervisors-rd
  jobEntity: BorgWarChassisGenericBlue
  applyTraits: false
